# Biodiversity Technologies 

## What are _Biodiversity Technologies_?

Biodiversity technologies are tools that allow researchers and others to study, monitor and
conserve biodiversity. These tools can be used to monitor a wide range of species, habitats, and ecosystems, potentially in (near) real-time and/or from a great distance away.

### What has enabled Biodiversity Technologies?

The development of biodiversity technologies has been enabled by the rapid advances in sensor technology, data processing, and communication networks. These technologies have made it possible to collect, store, and analyse large amounts of data from a wide range of sources, including remote sensors, cameras, and acoustic recorders.

This has been accompanied by a decline in the cost of these technologies (e.g. Figure  \@ref(fig:storage-costs)), making them more accessible to researchers, conservationists, and others interested in monitoring biodiversity.

```{r, storage-costs, echo=FALSE, fig.cap="The decline in storage costs per megabyte in consumer hard drives."}
library(figuREd)
storageCosts()
``` 

These technologies can potentially create vast datasets, and in order to adhere to the FAIR principles (Findable, Accessible, Interoperable, Reusable), it is important for the data to be accompanied by an appropriate suite of data standards, such as those developed by TDWG.

## Structure of Wildlife Systems

### Overall Philosophy

### Packages
