# Nodes

The fundamental unit of the WildlifeSystems platform is the node. A node is a physical device that can be used to collect data from sensors, control devices, and communicate with other nodes. Nodes are (typically) Raspberry Pi computers, packaged with an array of environmental sensors, microphone(s), and/or camera(s).

The WildlifeSystems software is used to configure a node to collect data from the sensors and what to do with the data collected. Typically this will be to send the data for external storage and analysis, but it is also possible to store the data locally on the node. Data can also be processed locally on the node, for example to detect a specific event (e.g. a sound or image) and then send a notification to the user. The WildlifeSystems software is designed to be modular, so that new sensors and devices can be added easily, and the data processing can be configured to suit the user's needs.

## Standard node

There is no such thing as a 'standard node', apart from the core software interfaces. In some deployments, however, there will be a great deal of standardisation.  The Urban Research Station deployment at the Natural History Museum, London, for example, has a number of nodes that are identically configured. Although even here, there are differences in the sensors used, and the data processing that is done. The nodes are all configured to send data to the same server (the Data Ecosystem) but the exact configuration of each node is driven by current research needs. In this way a network of WildlifeSystems nodes can be seen as a platform for facilitating research, rather than as a single-purpose device.

To make it easier to deploy and work with individual nodes, it is recommended that some commonly used sensors are deployed in the stadard fashion described below.

### Self-monitoring

Electricity and water should not mix. While suitable enclosures go a long way to preventing an unfortunate meeting, many nodes are deployed outside in the elements. The addition of a cheap DHT11 sensor internally to monitor the humidity and temperature of the enclosure may help identify a potentially damaging situation before it becomes problematic. [TODO: See PRTG integration].

This sensor is recommended to be attached to GPIO pin 4.

### i2s microphones

TODO

### 1-Wire bus

GPIO 17

## Enclosures

### Fixing inside enclosures

### Attaching sensors 

TODO: to sockets, not directly

TODO: breakout boards

TODO: custom boards

### Power solutions

TODO: PoE
