# Sound devices in WildlifeSystems

## Installing sound device support

Support for sound devices is installed as part of the node installation process, however it is possible to install the `sound-device-control` abstraction layer onto any Raspberry Pi system using the command below.

```{bash eval=FALSE}
`wget -O - https://github.com/wildlife-systems/sound-device-control/raw/master/install | sudo bash`
```

The installation will install the `alsa-utils` package on Ubuntu/Debian systems, and add the current user to the `audio` group.

## Supported sound devices

The WildlifeSystems platform supports several popular sound capture and playback devices. 

### Raspberry Pi onboard audio

### AudioInjector Zero

### AudioInjector Octo

### AudioInjector Ultra

### I2C microphone (e.g. Google Voice Hat)

Limited to 48kHz sample rate, no record volume control.

### Respeaker 6 mic array

### Audio+ DAC

### Wolfson Audio Card

## Installing a sound device

To install support for a sound device, run the following command.

```{bash eval=FALSE}
sdc-inst <sound-device-name>
```

To get a list of names of supported devices, run the following command.

```{bash eval=FALSE}
sdc-inst list
```
