# Supported sensors

## List of supported sensors

### BME680

4-in-1 sensor that provides humidity, temperature, pressure, and gas readings.

### DS18B20

The DS18B20 is a digital thermometer that provides Celsius measurements over a 1-Wire interface. It is a low-cost, low-power device that can be used for a variety of environmental monitoring applications. Waterproof versions are available, making it suitable for use in water and soils.

````{bash eval=FALSE}
sudo apt install sensor-ds18b20

sudo sr ds18b20
````

### DHT11

The DHT11 is a low-cost  temperature and humidity sensor. It uses a capacitive humidity sensor and a thermistor to measure the surrounding air, and sends the data by digital signals on the data pin.

The low-cost nature of the sensor makes it useful desp ite several shortcomings, e.g. for monitoring the temperature and humidity inside electronics enclosures where accuracy is not critical but the sensor can provide critical early warning of overheating or condensation.

````{bash eval=FALSE}
sudo apt install sensor-dht11

sudo sr dht11
````

### LV-MaxSonar-EZ

A series of ultrasonic distance sensors that can measure distances from 2 cm to 4 m with high accuracy. They are commonly used in robotics and automation applications, but can also be used for environmental monitoring.

````{bash eval=FALSE}
sudo apt install sensor-hrlv

sudo sr hrlv
````