# Return codes

The various scripts that form the WildlifeSystems ecosystem use a standard set of return codes.

## 00-09 Script functionality

````{r, echo=FALSE}
Code <- seq(from=0, to=2)
Label <- c(
  "OK",
  "Already running",
  "No arguments"
)
Description <- c(
  "Terminated normally. No error.",
  "The script determined it was already running and terminated.",
  "The script requires arguments but none given. Will give help text."
)
t <- cbind(Code, Label, Description)
knitr::kable(t)
````

## 10-19 Parameter problems

````{r, echo=FALSE}
Code <- seq(from=10, to=11)
Label <- c(
  "Invalid argument",
  "Incorrect filename pattern"
)
Description <- c(
  "One or more of the arguments to the script was invalid.",
  "A standard filename pattern was expected. Allowed values are 'timestamp'."
)
t <- cbind(Code, Label, Description)
knitr::kable(t)
````

## 20-29 Sensor problems

````{r, echo=FALSE}
Code <- seq(from=20, to=21)
Label <- c(
  "Unknown device",
  "Unknown sensor"
)
Description <- c(
  "This device is not supported, or software is not installed.",
  "This sensor is not known on this device."
)
t <- cbind(Code, Label, Description)
knitr::kable(t)
````

## 30-39 Sound device problems

````{r, echo=FALSE}
Code <- seq(from=30, to=32)
Label <- c(
  "Unsupported device",
  "Unsupported feature",
  "Unknown feature"
)
Description <- c(
  "The specified device is unsupported.",
  "This feature is not present on the sound device.",
  "The feature requested is unknown."
)
t <- cbind(Code, Label, Description)
knitr::kable(t)
````

## 40-49 Image device problems

````{r, echo=FALSE}
Code <- seq(from=40, to=42)
Label <- c(
  "Unsupported device",
  "Unsupported feature",
  "Unknown feature"
)
Description <- c(
  "The specified device is unsupported.",
  "This feature is not present on the sound device.",
  "The feature requested is unknown."
)
t <- cbind(Code, Label, Description)
knitr::kable(t)
````

## 50-59 Power management problems

````{r, echo=FALSE}
Code <- seq(from=50, to=51)
Label <- c(
  "Disallowed value (should be on or off)",
  "Disallowed value (should be on, off or default)"
)
Description <- c(
  "The specified device is unsupported.",
  "This feature is not present on the sound device."
)
t <- cbind(Code, Label, Description)
knitr::kable(t)
````

## 60-69 Special meanings

````{r, echo=FALSE}
Code <- seq(from=60, to=60)
Label <- c(
  "Identify as a sensor device script"
)
Description <- c(
  "Returned by sensor device script in response to first parameter `identify`."
)
t <- cbind(Code, Label, Description)
knitr::kable(t)
````
